services:
  cat-pinterest-api:
    container_name: cat-pinterest-api
    image: cat-pinterest-api
    build:
      context: ./api/
    networks:
      - cat-pinterest-net
    env_file:
      - ./api/.env.production
    environment:
      NODE_ENV: production
    depends_on:
      cat-pinterest-api-pg:
        condition: service_healthy

  cat-pinterest-front:
    container_name: cat-pinterest-front
    image: cat-pinterest-front
    build:
      context: ./frontend/
    networks:
      - cat-pinterest-net
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  cat-pinterest-api-pg:
    container_name: cat-pinterest-api-pg
    image: postgres:16
    networks:
      - cat-pinterest-net
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: support_lk_db
#    volumes:
#      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10

networks:
  cat-pinterest-net:
#
#volumes:
#  pg_data:
